# Generated by Django 5.0 on 2024-01-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_course_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
